apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: otel-symbolicator
  name: apps
---
apiVersion: v1
data:
  API_ENDPOINT: api.apps.svc.cluster.local
  CLICKHOUSE_HOST: clickhouse.database.svc.cluster.local
  CLICKHOUSE_PORT: "9000"
kind: ConfigMap
metadata:
  labels:
    app: otel-symbolicator
  name: otel-symbolicator-config-bf668kmm2g
  namespace: apps
---
apiVersion: v1
data:
  otel-symbolicator-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4319
            cors:
              allowed_origins:
                - http://*
                - https://*
              allowed_headers:
                - "*"
    processors:
      imqasymbolicateprocessor:
        api_endpoint: ${env:API_ENDPOINT}/api/v1/download/mappingFiles
        enabled: true
        # file_fetch_interval must be at least 60 seconds
        file_fetch_interval: 60s
        use_insecure: true
        file_base_dir: ./file
        use_atos: true
        use_proguard: true
        use_allatori: true
        use_app_suit: false
      batch:
        send_batch_size: 10000
        send_batch_max_size: 11000
        timeout: 10s

      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500 # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s # 50% of the maximum memory
        limit_percentage: 50 # 20% of max memory usage spike expected
        spike_limit_percentage: 20
      #  queued_retry:
      #     num_workers: 4
      #     queue_size: 100
      #     retry_on_failure: true

    exporters:
      clickhouse:
        username: ${env:CLICKHOUSE_USERNAME}
        password: ${env:CLICKHOUSE_PASSWORD}
        host: ${env:CLICKHOUSE_HOST}
        port: ${env:CLICKHOUSE_PORT}
        #    endpoint: tcp://host.docker.internal:9000
        traces_database: imqa_traces
        traces_table_name: stacktrace_symbolicated
        logs_database: imqa_logs
        logs_table_name: stacktrace_symbolicated
        table_engine:
          name: MergeTree
          params:


    service:
      telemetry:
        metrics:
          level: none
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, imqasymbolicateprocessor, batch ]
          exporters: [ clickhouse ]
        logs:
          receivers: [ otlp ]
          processors: [ memory_limiter, imqasymbolicateprocessor, batch ]
          exporters: [ clickhouse ]
kind: ConfigMap
metadata:
  labels:
    app: otel-symbolicator
  name: otel-symbolicator-config-yaml
  namespace: apps
---
apiVersion: v1
data:
  CLICKHOUSE_PASSWORD: ZGpzbHpqYTAwODA=
  CLICKHOUSE_USERNAME: ZGVmYXVsdA==
kind: Secret
metadata:
  labels:
    app: otel-symbolicator
  name: otel-symbolicator-secret-h6899ktmtm
  namespace: apps
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-symbolicator
  name: otel-symbolicator
  namespace: apps
spec:
  ports:
  - name: otlp-http
    port: 4319
    protocol: TCP
    targetPort: 4319
  selector:
    app: otel-symbolicator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel-symbolicator
  name: otel-symbolicator
  namespace: apps
spec:
  selector:
    matchLabels:
      app: otel-symbolicator
  template:
    metadata:
      labels:
        app: otel-symbolicator
    spec:
      containers:
      - args:
        - --config=/etc/otel-symbolicator-config.yaml
        envFrom:
        - configMapRef:
            name: otel-symbolicator-config-bf668kmm2g
        - secretRef:
            name: otel-symbolicator-secret-h6899ktmtm
        image: imqav3.azurecr.io/otel-symbolicator:4.0.0-rc.1
        imagePullPolicy: IfNotPresent
        name: otel-symbolicator
        ports:
        - containerPort: 4319
          name: otlp-http
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - mountPath: /etc/otel-symbolicator-config.yaml
          name: config-volume
          subPath: otel-symbolicator-config.yaml
      volumes:
      - configMap:
          name: otel-symbolicator-config-yaml
        name: config-volume
