apiVersion: v1
kind: ConfigMap
metadata:
  name: imqa-api-config
  namespace: api
data:
  QUERY_SERVICE_CLICKHOUSE_TTL: "2592000"
  QUERY_SERVICE_CLICKHOUSE_QUERY_LOG_ENABLED: "false"
  QUERY_SERVICE_STORAGE: "clickhouse"
  QUERY_SERVICE_TELEMETRY_ENABLED: "false"
  QUERY_SERVICE_API_ENDPOINT: "http://api.api.svc.cluster.local:8000"
  GODEBUG: "netdns=go"
  DEPLOYMENT_TYPE: "docker-standalone-amd"
