apiVersion: v1
kind: Service
metadata:
  name: imqa-api
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: imqa-api
  ports:
  - name: public
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: private
    port: 8085
    targetPort: 8085
    protocol: TCP
