apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  namespace: api
spec:
  serviceName: "api"
  replicas: 1
  selector:
    matchLabels:
      app: api
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "openebs-lvmpv"
      resources:
        requests:
          storage: 500Gi
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        kubernetes.io/hostname: imqa-web
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: api
      restartPolicy: Always
      containers:
        - name: api
          image: imqav3.azurecr.io/api:1.5.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          volumeMounts:
            - mountPath: /app/uploads
              name: data
            - mountPath: /app/config/saml/
              name: config-volume
      volumes:
        - name: config-volume
          emptyDir: {}
      terminationGracePeriodSeconds: 30
