apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: database
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/name: postgresql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "openebs-lvmpv"
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: postgresql
        app.kubernetes.io/name: postgresql
    spec:
      nodeSelector:
        kubernetes.io/hostname: imqa-database
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "database"
        effect: "NoSchedule"
      serviceAccountName: postgresql
      containers:
        - name: postgresql
          image: postgres:17.2-alpine3.21
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: apidb
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 192Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir: { medium: Memory }
