apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse
  namespace: database
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql
  namespace: database
automountServiceAccountToken: false
