apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      nodeSelector:
        kubernetes.io/hostname: imqa-collector
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "collector"
        effect: "NoSchedule"
      containers:
        - name: otel-collector
          image: imqav3.azurecr.io/otel-collector:1.5.5
          imagePullPolicy: IfNotPresent
          args:
            - --config=/etc/otel-collector-config.yaml
          envFrom:
            - configMapRef:
                name: otel-collector-config
            - secretRef:
                name: otel-collector-secret
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 2255
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
            - containerPort: 8889
              protocol: TCP
            - containerPort: 55679
              protocol: TCP
            - containerPort: 13133
              protocol: TCP
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
