apiVersion: v1
kind: Namespace
metadata:
  name: api

---

apiVersion: v1
kind: Namespace
metadata:
  name: collector

---

apiVersion: v1
kind: Namespace
metadata:
  name: database

---

apiVersion: v1
kind: Namespace
metadata:
  name: openebs
