apiVersion: batch/v1
kind: Job
metadata:
  name: otel-migrator-job
  namespace: collector
spec:
  template:
    metadata:
      name: otel-migrator
    spec:
      nodeSelector:
        kubernetes.io/hostname: imqa-collector
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "collector"
        effect: "NoSchedule" 
      restartPolicy: Never
      containers:
      - name: otel-migrator
        image: imqav3.azurecr.io/otel-migrator:1.5.5
        imagePullPolicy: IfNotPresent
        env:
        - name: CLICKHOUSE_DSN
          valueFrom:
            secretKeyRef:
              name: otel-collector-secret
              key: OTEL_COLLECTOR_CLICKHOUSE_DSN
        args:
          - --dsn
          - "$(CLICKHOUSE_DSN)"
