apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-symbolicator-config
  namespace: collector
data:
  OTEL_COLLECTOR_SYMBOLICATOR_API_ENDPOINT: http://api

  otel-collector-symbolicator-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4319
            cors:
              allowed_origins:
                - http://*
                - https://*
              allowed_headers:
                - "*"
    processors:
      imqasymbolicateprocessor:
        api_endpoint: ${env:OTEL_COLLECTOR_SYMBOLICATOR_API_ENDPOINT}/api/v1/download/mappingFiles
        enabled: true
        file_fetch_interval: 60s
        use_insecure: true
        file_base_dir: ./file
        use_atos: true
        use_proguard: true
        use_allatori: true
        use_app_suit: false
      batch:
        send_batch_size: 10000
        send_batch_max_size: 11000
        timeout: 10s
      memory_limiter:
        limit_mib: 1500
        spike_limit_mib: 512
        check_interval: 5s
        limit_percentage: 50
        spike_limit_percentage: 20
    exporters:
      clickhouse:
        endpoint: ${env:OTEL_COLLECTOR_SYMBOLICATOR_CLICKHOUSE_DSN}
        traces_database: imqa_traces
        traces_table_name: stacktrace_symbolicated
        logs_database: imqa_logs
        logs_table_name: stacktrace_symbolicated
        table_engine:
          name: MergeTree
          params:
    service:
      telemetry:
        metrics:
          level: none
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, imqasymbolicateprocessor, batch ]
          exporters: [ clickhouse ]
        logs:
          receivers: [ otlp ]
          processors: [ memory_limiter, imqasymbolicateprocessor, batch ]
          exporters: [ clickhouse ]
